### ISSUE TITLE
resourceGroup().name should be changed to parameter

### ISSUE THREAD

**Issue by kemurayama** [hiroyay-ms/Deploying-to-Azure-for-CSA#26]
resourceGroup().name にした場合、az deployment group で指定した resource group となるため、ハンズオンの中で新規リソース グループを作成すると GitHub Actions の中で失敗してしまいます。
このため、指定するときはパラメータのほうが良いかと感じました。

https://github.com/hiroyay-ms/Deploying-to-Azure/blob/03978cc940c69e75e24efe19931c19d1d4d297ec/Hands-on-Lab/templates/deploy-vm-as-domain-member.json#L86

**Comment by hiroyay-ms** [comment]
VNet の Resource Group を指定できるよう ARM テンプレートを変更済み
